### ISSUE TITLE
app/build.gradle file  minimum sdk version

### ISSUE THREAD

**Issue by Mo-Shehri** [SEG2105-Group/JobZi#44]
Make sure the minSdkVersion is 15 and is compatible with the code

**Comment by RawadAboudlal** [comment]
According this screenshot ![Screenshot of project requirement document, only including the part about the SDK version](https://user-images.githubusercontent.com/11742995/48107838-1173f900-e20f-11e8-9078-5bbeffa5aa04.png) from the project requirement document (the general one), it turns out that you should us the "earliest possible SDK version allowed by the API methods you are using". They do not specify SDK 15, which is annoying, and we will keep the minimum SDK version to that, but basically the document says we *can* use more advanced features available to newer SDK's without a problem (though we probably will not because of how ambiguous they are about this).
